### ISSUE TITLE
糖糕云也可每日签到获得面板服

### ISSUE THREAD

**Issue by hehysh** [xjh2009/all-sign-renew#1]
佬，能否增加糖糕云自动签到脚本

**Comment by xjh2009** [comment]
那东西要实名吧 我不想碰带实名的

发送自 Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: He Hao Yang ***@***.***>
Sent: Monday, August 12, 2024 10:22:10 PM
To: xjh2009/all-sign-renew ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xjh2009/all-sign-renew] 糖糕云也可每日签到获得面板服 (Issue #1)


佬，能否增加糖糕云自动签到脚本

―

**Comment by hehysh** [comment]
糖糕云获取积分，兑换面板服时不需实名。需要实名是购买国内vps服务器以及注册api密钥时。但是那个api密钥是为了代理商准备的，本身应该是和签到无关的。

**Comment by xjh2009** [comment]
已经写完了 我在旅游 所以要有时间才能发

发送自 Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
